create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.weight_entries (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  weight_kg numeric not null check (weight_kg > 0),
  recorded_at timestamptz not null,
  note text
);

create index if not exists weight_entries_person_recorded_idx
  on public.weight_entries (person_id, recorded_at);

-- Development mode:
-- Keep Row Level Security disabled only while testing a shared family/group
-- database. Before publishing the app, add Supabase Auth and enable RLS.
alter table public.people disable row level security;
alter table public.weight_entries disable row level security;
